/**
 * 隐藏宝箱: where the hidden chests stand (the kernel opens them, the client draws them). Nooks beside the drawn
 * layout (src/shared/layout.ts): behind a courtyard pillar, in a corner of the Great Hall, behind the greenhouse,
 * Hagrid's back garden, the stands, Hogsmeade's back alleys, the Shrieking Shack... test/fun.test.ts checks that
 * each one stands clear of every collider, on dry land, inside the walkable world. They refill every term.
 */
export interface ChestSpot { id: string; x: number; z: number; zh: string; en: string }

/** Opening a chest pays this much experience (once per chest per term). */
export const CHEST_XP = 8;

export const CHESTS: ChestSpot[] = [
  { id: 'pillar', x: -21, z: -33, zh: '庭院石柱后面', en: 'Behind a courtyard pillar' },
  { id: 'hall', x: -10.4, z: -70.2, zh: '礼堂的角落', en: 'A corner of the Great Hall' },
  { id: 'greenhouse', x: 41, z: -47, zh: '温室背后', en: 'Behind Greenhouse Three' },
  { id: 'tomb', x: -49.5, z: 32.5, zh: '白色大理石墓旁', en: 'Beside the white tomb' },
  { id: 'hagrid', x: 101, z: 37, zh: '海格的菜园', en: "Hagrid's pumpkin patch" },
  { id: 'stands', x: 72, z: -150, zh: '魁地奇看台下', en: 'Under the Quidditch stands' },
  { id: 'honeydukes', x: 21, z: 146, zh: '蜂蜜公爵后巷', en: 'The alley behind Honeydukes' },
  { id: 'shack', x: 64, z: 211, zh: '尖叫棚屋门口', en: 'The Shrieking Shack\'s porch' },
  { id: 'lakeshore', x: -58, z: 4, zh: '黑湖岸边的芦苇丛', en: 'Reeds on the Black Lake shore' },
  { id: 'willow', x: 54, z: 7, zh: '打人柳够不着的地方', en: 'Just out of the Willow\'s reach' },
  { id: 'trail', x: 130, z: 17, zh: '禁林小径', en: 'The Forbidden Forest trail' },
  { id: 'seventh', x: -42, z: -54, zh: '八楼走廊尽头', en: 'The end of the seventh-floor corridor' },
  { id: 'broomsticks', x: -23, z: 165, zh: '三把扫帚酒吧后院', en: 'Behind the Three Broomsticks' },
  { id: 'clock', x: 71, z: -60, zh: '钟楼脚下', en: 'At the foot of the Clock Tower' },
{ id: 'castle-01', x: -55.9, z: -55.3, zh: '废弃教室的讲台下', en: 'Under the desk in an abandoned classroom' },
  { id: 'castle-02', x: -55.4, z: -59.6, zh: '画像后面的暗格', en: 'The alcove behind a portrait' },
  { id: 'castle-03', x: -60.7, z: -56.8, zh: '盔甲旁边的壁龛', en: 'The niche beside a suit of armor' },
  { id: 'castle-04', x: -55.1, z: -57.5, zh: '楼梯转角的阴影里', en: 'In the shadow of a stairwell turn' },
  { id: 'castle-05', x: -60.3, z: -58.1, zh: '走廊尽头的窗台下', en: 'Under the windowsill at the corridor\'s end' },
  { id: 'castle-06', x: -53.4, z: -57.3, zh: '石柱后面的角落', en: 'The corner behind a stone pillar' },
  { id: 'castle-07', x: -61.3, z: -62.3, zh: '图书馆书架尽头', en: 'At the end of a library shelf' },
  { id: 'castle-08', x: -58.1, z: -62.9, zh: '楼梯下的储物间门口', en: 'By the broom closet under the stairs' },
  { id: 'castle-09', x: -58.5, z: -61.8, zh: '阳台角落的花盆后', en: 'Behind a planter in a balcony corner' },
  { id: 'castle-10', x: -52.3, z: -62.3, zh: '魔药教室外的凹室', en: 'The recess outside the Potions classroom' },
  { id: 'castle-11', x: -57.9, z: -34.7, zh: '变形课教室后排', en: 'The back row of the Transfiguration classroom' },
  { id: 'castle-12', x: -53.9, z: -42.3, zh: '黑魔法防御术走廊拐角', en: 'The DADA corridor corner' },
  { id: 'castle-13', x: -56.9, z: -35.1, zh: '校医院门口的长椅下', en: 'Under the bench by the hospital wing' },
  { id: 'castle-14', x: -55.1, z: -44.9, zh: '猫头鹰棚屋下的阴影', en: 'In the shadow under the Owlery' },
  { id: 'castle-15', x: -56.3, z: -45.1, zh: '厨房入口的桶后面', en: 'Behind a barrel by the kitchen entrance' },
  { id: 'castle-16', x: -55.2, z: -41, zh: '门厅的火炬座后面', en: 'Behind a torch sconce in the Entrance Hall' },
  { id: 'castle-17', x: -55.2, z: -43, zh: '大理石楼梯的扶手下', en: 'Under the marble staircase railing' },
  { id: 'castle-18', x: -58.5, z: -41, zh: ' trophy 陈列室的角落', en: 'A corner of the trophy room' },
  { id: 'castle-19', x: -58.1, z: -33.8, zh: '决斗俱乐部的旧垫子后', en: 'Behind old mats of the Duelling Club' },
  { id: 'castle-20', x: -58, z: -46.1, zh: '占卜课塔楼的楼梯口', en: 'The Divination tower stairwell mouth' },
  { id: 'castle-21', x: -59.9, z: -44.6, zh: '废弃教室的讲台下', en: 'Under the desk in an abandoned classroom' },
  { id: 'castle-22', x: -55.5, z: -46.3, zh: '画像后面的暗格', en: 'The alcove behind a portrait' },
  { id: 'castle-23', x: -59.5, z: -42.6, zh: '盔甲旁边的壁龛', en: 'The niche beside a suit of armor' },
  { id: 'castle-24', x: -58.1, z: -43.5, zh: '楼梯转角的阴影里', en: 'In the shadow of a stairwell turn' },
  { id: 'castle-25', x: -54.1, z: -40, zh: '走廊尽头的窗台下', en: 'Under the windowsill at the corridor\'s end' },
  { id: 'castle-26', x: -56.1, z: -37, zh: '石柱后面的角落', en: 'The corner behind a stone pillar' },
  { id: 'castle-27', x: -62.3, z: -39, zh: '图书馆书架尽头', en: 'At the end of a library shelf' },
  { id: 'castle-28', x: -57.8, z: -39.6, zh: '楼梯下的储物间门口', en: 'By the broom closet under the stairs' },
  { id: 'castle-29', x: -55.5, z: -42.5, zh: '阳台角落的花盆后', en: 'Behind a planter in a balcony corner' },
  { id: 'castle-30', x: -57.4, z: -11.4, zh: '魔药教室外的凹室', en: 'The recess outside the Potions classroom' },
  { id: 'castle-31', x: -60.4, z: -17.2, zh: '变形课教室后排', en: 'The back row of the Transfiguration classroom' },
  { id: 'castle-32', x: -53, z: -16, zh: '黑魔法防御术走廊拐角', en: 'The DADA corridor corner' },
  { id: 'castle-33', x: -62.4, z: -15.6, zh: '校医院门口的长椅下', en: 'Under the bench by the hospital wing' },
  { id: 'castle-34', x: -55.7, z: -18.8, zh: '猫头鹰棚屋下的阴影', en: 'In the shadow under the Owlery' },
  { id: 'castle-35', x: -54.1, z: -15, zh: '厨房入口的桶后面', en: 'Behind a barrel by the kitchen entrance' },
  { id: 'castle-36', x: -59.5, z: -13.6, zh: '门厅的火炬座后面', en: 'Behind a torch sconce in the Entrance Hall' },
  { id: 'castle-37', x: -52, z: -17.6, zh: '大理石楼梯的扶手下', en: 'Under the marble staircase railing' },
  { id: 'castle-38', x: -55.4, z: -12.7, zh: ' trophy 陈列室的角落', en: 'A corner of the trophy room' },
  { id: 'castle-39', x: -56.5, z: -14.9, zh: '决斗俱乐部的旧垫子后', en: 'Behind old mats of the Duelling Club' },
  { id: 'castle-40', x: -61.6, z: -11.7, zh: '占卜课塔楼的楼梯口', en: 'The Divination tower stairwell mouth' },
  { id: 'lake-01', x: -109.3, z: 3.5, zh: '湖岸的礁石缝里', en: 'Wedged between lakeshore rocks' },
  { id: 'lake-02', x: -107, z: 8.9, zh: '芦苇丛深处', en: 'Deep in the reeds' },
  { id: 'lake-03', x: -107.9, z: 9.5, zh: '浅滩的倒木下', en: 'Under a fallen log in the shallows' },
  { id: 'lake-04', x: -108.4, z: 8.9, zh: '湖边小码头的木板下', en: 'Under the planks of the lakeside jetty' },
  { id: 'lake-05', x: -107.3, z: 5.3, zh: '半淹没的岩石后面', en: 'Behind a half-submerged rock' },
  { id: 'lake-06', x: -109.8, z: 4.3, zh: '湖岸柳树的根部', en: 'At the roots of a lakeside willow' },
  { id: 'lake-07', x: -105.4, z: 9.1, zh: '人鱼雕像的底座旁', en: 'Beside the merfolk statue\'s plinth' },
  { id: 'lake-08', x: -104.9, z: 10.8, zh: '湖岸小径的拐弯处', en: 'Where the shore path bends' },
  { id: 'lake-09', x: -106.2, z: 9.5, zh: '湖岸的礁石缝里', en: 'Wedged between lakeshore rocks' },
  { id: 'lake-10', x: -108, z: 1.3, zh: '芦苇丛深处', en: 'Deep in the reeds' },
  { id: 'lake-11', x: -108.3, z: 6.3, zh: '浅滩的倒木下', en: 'Under a fallen log in the shallows' },
  { id: 'lake-12', x: -105.8, z: 7.8, zh: '湖边小码头的木板下', en: 'Under the planks of the lakeside jetty' },
  { id: 'lake-13', x: -105.7, z: 5.9, zh: '半淹没的岩石后面', en: 'Behind a half-submerged rock' },
  { id: 'lake-14', x: -105.6, z: 2.5, zh: '湖岸柳树的根部', en: 'At the roots of a lakeside willow' },
  { id: 'lake-15', x: -105.6, z: 5.4, zh: '人鱼雕像的底座旁', en: 'Beside the merfolk statue\'s plinth' },
  { id: 'forest-01', x: 85, z: -4.2, zh: '大树后面的树洞旁', en: 'By a hollow behind a great tree' },
  { id: 'forest-02', x: 85.2, z: -6.5, zh: '空地边缘的灌木丛', en: 'In the bushes at the clearing\'s edge' },
  { id: 'forest-03', x: 84.4, z: -6.9, zh: '蜘蛛巢附近的岩石后', en: 'Behind rocks near the spider nest' },
  { id: 'forest-04', x: 83.4, z: -5.3, zh: '倒下的古树树干下', en: 'Under a fallen ancient trunk' },
  { id: 'forest-05', x: 89.9, z: -4.1, zh: '发光蘑菇圈的中央', en: 'At the center of a glowing mushroom ring' },
  { id: 'forest-06', x: 86.5, z: -3.1, zh: '独角兽饮水池边', en: 'By the unicorn watering pool' },
  { id: 'forest-07', x: 88.6, z: -7, zh: '马人营地的外围', en: 'On the outskirts of the centaur camp' },
  { id: 'forest-08', x: 86.2, z: -5.8, zh: '密林深处的藤蔓后', en: 'Behind vines deep in the thicket' },
  { id: 'forest-09', x: 83.6, z: -2.6, zh: '猎场看守小径的岔口', en: 'Where the gamekeeper\'s trail forks' },
  { id: 'forest-10', x: 85.2, z: -9.4, zh: '禁林雾气最浓的地方', en: 'Where the forest mist lies thickest' },
  { id: 'forest-11', x: 87.2, z: -6.4, zh: '大树后面的树洞旁', en: 'By a hollow behind a great tree' },
  { id: 'forest-12', x: 83.3, z: -8.4, zh: '空地边缘的灌木丛', en: 'In the bushes at the clearing\'s edge' },
  { id: 'forest-13', x: 83.5, z: -8.5, zh: '蜘蛛巢附近的岩石后', en: 'Behind rocks near the spider nest' },
  { id: 'forest-14', x: 88.4, z: -4, zh: '倒下的古树树干下', en: 'Under a fallen ancient trunk' },
  { id: 'forest-15', x: 87.9, z: -6.7, zh: '发光蘑菇圈的中央', en: 'At the center of a glowing mushroom ring' },
  { id: 'forest-16', x: 84.2, z: -5.8, zh: '独角兽饮水池边', en: 'By the unicorn watering pool' },
  { id: 'forest-17', x: 89.6, z: -7, zh: '马人营地的外围', en: 'On the outskirts of the centaur camp' },
  { id: 'forest-18', x: 83.3, z: -2.6, zh: '密林深处的藤蔓后', en: 'Behind vines deep in the thicket' },
  { id: 'forest-19', x: 85.2, z: -1.9, zh: '猎场看守小径的岔口', en: 'Where the gamekeeper\'s trail forks' },
  { id: 'forest-20', x: 87, z: 10.8, zh: '禁林雾气最浓的地方', en: 'Where the forest mist lies thickest' },
  { id: 'forest-21', x: 84.5, z: 9, zh: '大树后面的树洞旁', en: 'By a hollow behind a great tree' },
  { id: 'forest-22', x: 84.9, z: 9.6, zh: '空地边缘的灌木丛', en: 'In the bushes at the clearing\'s edge' },
  { id: 'forest-23', x: 84.7, z: 7.4, zh: '蜘蛛巢附近的岩石后', en: 'Behind rocks near the spider nest' },
  { id: 'forest-24', x: 88.1, z: 7.4, zh: '倒下的古树树干下', en: 'Under a fallen ancient trunk' },
  { id: 'forest-25', x: 87.8, z: 8.6, zh: '发光蘑菇圈的中央', en: 'At the center of a glowing mushroom ring' },
  { id: 'forest-26', x: 88.4, z: 3.6, zh: '独角兽饮水池边', en: 'By the unicorn watering pool' },
  { id: 'forest-27', x: 83.5, z: 7.2, zh: '马人营地的外围', en: 'On the outskirts of the centaur camp' },
  { id: 'forest-28', x: 86.1, z: 6.2, zh: '密林深处的藤蔓后', en: 'Behind vines deep in the thicket' },
  { id: 'forest-29', x: 87.8, z: 8.2, zh: '猎场看守小径的岔口', en: 'Where the gamekeeper\'s trail forks' },
  { id: 'forest-30', x: 86.9, z: 6, zh: '禁林雾气最浓的地方', en: 'Where the forest mist lies thickest' },
  { id: 'pitch-01', x: 3.3, z: -182.9, zh: '看台下的支撑柱后', en: 'Behind a support pillar under the stands' },
  { id: 'pitch-02', x: 5, z: -184.8, zh: '更衣室门口的长凳下', en: 'Under the bench by the changing room' },
  { id: 'pitch-03', x: 8.7, z: -175, zh: '球门柱旁的草丛', en: 'In the grass by a goalpost' },
  { id: 'pitch-04', x: 5.2, z: -183.4, zh: '记分牌后面的检修口', en: 'The service hatch behind the scoreboard' },
  { id: 'pitch-05', x: 8.2, z: -185.5, zh: '解说台下的储物格', en: 'A storage nook under the commentary box' },
  { id: 'pitch-06', x: -0.9, z: -183.4, zh: '球员通道的拐角', en: 'The players\' tunnel corner' },
  { id: 'pitch-07', x: 2.9, z: -174.9, zh: '格兰芬多看台的最后一排', en: 'The last row of the Gryffindor stand' },
  { id: 'pitch-08', x: 9.1, z: -189.2, zh: '看台下的支撑柱后', en: 'Behind a support pillar under the stands' },
  { id: 'pitch-09', x: 3.1, z: -183.8, zh: '更衣室门口的长凳下', en: 'Under the bench by the changing room' },
  { id: 'pitch-10', x: 0.5, z: -175.5, zh: '球门柱旁的草丛', en: 'In the grass by a goalpost' },
  { id: 'pitch-11', x: 1.8, z: -174.7, zh: '记分牌后面的检修口', en: 'The service hatch behind the scoreboard' },
  { id: 'pitch-12', x: 6.4, z: -174.1, zh: '解说台下的储物格', en: 'A storage nook under the commentary box' },
  { id: 'pitch-13', x: 7.1, z: -182.4, zh: '球员通道的拐角', en: 'The players\' tunnel corner' },
  { id: 'pitch-14', x: 5.8, z: -175.6, zh: '格兰芬多看台的最后一排', en: 'The last row of the Gryffindor stand' },
  { id: 'pitch-15', x: 1.9, z: -177.4, zh: '看台下的支撑柱后', en: 'Behind a support pillar under the stands' },
  { id: 'hogsmeade-01', x: -34.2, z: 140.5, zh: '小巷深处的墙角', en: 'A corner deep in the alley' },
  { id: 'hogsmeade-02', x: -34.7, z: 133.5, zh: '蜂蜜公爵后门的台阶下', en: 'Under the steps of Honeydukes\' back door' },
  { id: 'hogsmeade-03', x: -30.6, z: 142.1, zh: '三把扫帚的马厩旁', en: 'Beside the Three Broomsticks\' stable' },
  { id: 'hogsmeade-04', x: -40.9, z: 140.9, zh: '尖叫棚屋篱笆的缺口', en: 'A gap in the Shrieking Shack\'s fence' },
  { id: 'hogsmeade-05', x: -37.8, z: 143.1, zh: '佐科笑话店的橱窗后', en: 'Behind Zonko\'s display window' },
  { id: 'hogsmeade-06', x: -32.7, z: 144.8, zh: '猪头酒吧的侧门旁', en: 'By the Hog\'s Head side door' },
  { id: 'hogsmeade-07', x: -35.1, z: 143.9, zh: '村口水井的石沿下', en: 'Under the stone rim of the village well' },
  { id: 'hogsmeade-08', x: -38.8, z: 134, zh: '德维斯班斯店后的柴堆', en: 'The woodpile behind Dervish and Banges' },
  { id: 'hogsmeade-09', x: -38.5, z: 144.2, zh: '文人居羽毛笔店的后巷', en: 'The back lane of Scrivenshaft\'s' },
  { id: 'hogsmeade-10', x: -31.9, z: 135.9, zh: '帕笛芙夫人的茶馆后院', en: 'The back yard of Madam Puddifoot\'s' },
  { id: 'hogsmeade-11', x: -37.4, z: 143.6, zh: '小巷深处的墙角', en: 'A corner deep in the alley' },
  { id: 'hogsmeade-12', x: -32.2, z: 141.4, zh: '蜂蜜公爵后门的台阶下', en: 'Under the steps of Honeydukes\' back door' },
  { id: 'hogsmeade-13', x: -33, z: 134.9, zh: '三把扫帚的马厩旁', en: 'Beside the Three Broomsticks\' stable' },
  { id: 'hogsmeade-14', x: -31.5, z: 143.1, zh: '尖叫棚屋篱笆的缺口', en: 'A gap in the Shrieking Shack\'s fence' },
  { id: 'hogsmeade-15', x: -32.3, z: 135.3, zh: '佐科笑话店的橱窗后', en: 'Behind Zonko\'s display window' },
  { id: 'hogsmeade-16', x: -38.3, z: 136.9, zh: '猪头酒吧的侧门旁', en: 'By the Hog\'s Head side door' },
  { id: 'hogsmeade-17', x: -35.6, z: 138.8, zh: '村口水井的石沿下', en: 'Under the stone rim of the village well' },
  { id: 'hogsmeade-18', x: -40.4, z: 136.6, zh: '德维斯班斯店后的柴堆', en: 'The woodpile behind Dervish and Banges' },
  { id: 'hogsmeade-19', x: -33.9, z: 144.2, zh: '文人居羽毛笔店的后巷', en: 'The back lane of Scrivenshaft\'s' },
  { id: 'hogsmeade-20', x: -39, z: 154.6, zh: '帕笛芙夫人的茶馆后院', en: 'The back yard of Madam Puddifoot\'s' },
  { id: 'hogsmeade-21', x: -38.2, z: 164.3, zh: '小巷深处的墙角', en: 'A corner deep in the alley' },
  { id: 'hogsmeade-22', x: -35.4, z: 162.4, zh: '蜂蜜公爵后门的台阶下', en: 'Under the steps of Honeydukes\' back door' },
  { id: 'hogsmeade-23', x: -34.5, z: 155.6, zh: '三把扫帚的马厩旁', en: 'Beside the Three Broomsticks\' stable' },
  { id: 'hogsmeade-24', x: -31.8, z: 159.8, zh: '尖叫棚屋篱笆的缺口', en: 'A gap in the Shrieking Shack\'s fence' },
  { id: 'hogsmeade-25', x: -33.7, z: 162.2, zh: '佐科笑话店的橱窗后', en: 'Behind Zonko\'s display window' },
  { id: 'hogsmeade-26', x: -37.4, z: 155.6, zh: '猪头酒吧的侧门旁', en: 'By the Hog\'s Head side door' },
];
