import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from '/workspace/Hogwarts/node_modules/three/build/three.module.js';
import { Water } from '/workspace/Hogwarts/node_modules/three/examples/jsm/objects/Water.js';
import { createLakeQuality } from './lake-quality-candidate.ts';
function fixture(){const lake=new Water(new THREE.PlaneGeometry(2,2),{waterColor:0x1a4f60});const original=lake.onBeforeRender;let mirrorCalls=0;const mirror:typeof original=(..._args)=>{mirrorCalls++;};const apply=process.env.CANDIDATE==='0'?((q:'low'|'high')=>{lake.onBeforeRender=q==='high'?mirror:()=>{};}):createLakeQuality(lake,mirror);let renderCalls=0;const renderer=new Proxy({},{get(_t,name){if(name==='render')return()=>{renderCalls++;};throw new Error('Low quality must not access renderer '+String(name));}});const scene=new THREE.Scene(),parent=new THREE.Group(),camera=new THREE.PerspectiveCamera();parent.position.set(-100,4,30);parent.add(camera);camera.position.set(17,11,9);parent.updateMatrixWorld(true);const draw=()=>lake.onBeforeRender(renderer as never,scene,camera,lake.geometry,lake.material,null);return{lake,apply,camera,parent,draw,counts:()=>({renderCalls,mirrorCalls})};}
test('cold low binds initialized linear color and updates eye from camera world matrix without a render pass',()=>{const f=fixture();assert.deepEqual(f.lake.material.uniforms.eye.value.toArray(),[0,0,0]);f.apply('low');f.draw();const u=f.lake.material.uniforms;assert.deepEqual(u.eye.value.toArray(),[-83,15,39]);const texture=u.mirrorSampler.value as THREE.DataTexture;assert.equal(texture.isDataTexture,true);assert.equal(texture.image.width,1);assert.equal(texture.image.height,1);assert.equal(texture.version,1);assert.equal(texture.colorSpace,THREE.NoColorSpace);assert.equal(texture.generateMipmaps,false);const linear=new THREE.Color(0x1a4f60);assert.deepEqual([...texture.image.data],[Math.round(linear.r*255),Math.round(linear.g*255),Math.round(linear.b*255),255]);assert.notEqual(texture.image.data[0],0x1a,'do not upload sRGB bytes as linear samples');assert.deepEqual(u.textureMatrix.value.elements,new THREE.Matrix4().elements);assert.deepEqual(f.counts(),{renderCalls:0,mirrorCalls:0});assert.equal((f.lake.onBeforeRender as any).lighter,true);});
test('low-high-low restores the same RT sampler and reuses the single low texture',()=>{const f=fixture(),u=f.lake.material.uniforms,rt=u.mirrorSampler.value;f.apply('low');const flat=u.mirrorSampler.value;f.draw();f.apply('high');assert.equal(u.mirrorSampler.value,rt);f.draw();assert.equal(f.counts().mirrorCalls,1);u.textureMatrix.value.makeTranslation(5,6,7);f.apply('low');assert.equal(u.mirrorSampler.value,flat);assert.deepEqual(u.textureMatrix.value.elements,new THREE.Matrix4().elements);f.camera.position.set(10,7,2);f.parent.updateMatrixWorld(true);f.draw();assert.deepEqual(u.eye.value.toArray(),[-90,11,32]);assert.equal(f.counts().renderCalls,0);assert.equal(f.counts().mirrorCalls,1);});
test('disposing the owning Water material releases the low texture once',()=>{const f=fixture();f.apply('low');const tex=f.lake.material.uniforms.mirrorSampler.value as THREE.DataTexture;let count=0;tex.addEventListener('dispose',()=>count++);f.lake.material.dispose();f.lake.material.dispose();assert.equal(count,1);});
